workspace:
  base: /go
  path: src/github.com/drone-demos/drone-go-postgres
  
pipeline:
  build:
    image: golang:1.8
    commands:
      - sleep 10
      - cd todo
      - go get -v
      - go test -v -cover
  notify:
    image: plugins/slack
    username: drone
    channel: nottesting
    webhook: https://hooks.slack.com/services/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
    icon_url: https://pbs.twimg.com/profile_images/573911705505259520/rShq67tG.png
    template: "Build #{{build.number}} for {{repo.name}} on branch {{build.branch}} resulting from {{build.event}} started at {{build.started}} has finished in {{build.status}}! Details here: {{build.link}}"
    when:
      status: [ success, failure ]
      event: [ push, tag, deployment, pull_request ]

services:
  database:
    image: postgres:9
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo
